routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

use Illuminate\Support\Facades\Route;
//Route::get('/',function (){
//    return view('front-end.index');
//
//})->name('home');

Route::get('/about', function () {
    return view('front-end.about');
})->name('about');
Route::get('/blog', function () {
    return view('front-end.blog');
})->name('blog');
//Route::get('/carts', function () {
//    return view('front-end.cart');
//})->name('carts');

Route::get('carts','AddtocartController@viewcart')->name('carts');
Route::get('/category', function () {
    return view('front-end.category');
})->name('category');
//Route::get('/checkout', function () {
//    return view('front-end.checkout');
//})->name('checkout');
Route::get('/confirmation', function () {
    return view('front-end.confirmation');
})->name('confirmation');
Route::get('/checkout_login', function () {
    return view('front-end.login');
})->name('checkout_login');
Route::get('/single-blog', function () {
    return view('front-end.single-blog');
})->name('single-blog');
Route::get('/single-product', function () {
    return view('front-end.single-product');
})->name('single-product');
Route::get('/elements', function () {
    return view('front-end.elements');
})->name('elements');
Route::get('/tracking', function () {
    return view('front-end.tracking');
})->name('tracking');
//Route::get('/', function () {
//    return view('front-end.index');
//})->name('profile');
Route::get('/category', function () {
    return view('front-end.category');
})->name('category');
Route::get('/profile', function () {
    return view('back-end.admin');
})->name('profile');

Route::get('/contacts', function () {
    return view('front-end.contact');
})->name('contacts');
Route::resource('brand','BrandController');
Route::resource('productlist','ProductlistController');
Route::resource('producte','producteController');
Route::resource('banners','BannerController');
Route::resource('cart','CartController');
Route::resource('categorie','CategorieController');
Route::resource('label','LabelController');
Route::resource('contact','ContactController');
Route::resource('map_product_tags','MapProductTagController');
Route::resource('order','OrderController');
Route::resource('page','PagesController');
Route::resource('populartag','PopularTagController');
Route::resource('slider','SliderController');
Route::resource('sponser','SponserController');
Route::resource('subscriber','SubscriberController');
Route::resource('tag','TagController');
Route::resource('testimonial','TestimonialController');
Route::resource('admin','AdminController');
Route::get('/winter','TestController@index')->name('index');
Route::resource('winter','WinterHomeController');
Route::resource('category','WinterCategoryController');
Route::resource('singlebrand','SingleBrandController');
Route::resource('singleproduct','SingleProductController');
Route::resource('checkout','checkoutController');
Route::resource('billinginfo','BillinfoController');
Route::post('paycheckout','PaycheckoutController@pay')->name('paycheckout');
Route::get('payindex','PaycheckoutController@index')->name('payindex');

//Route::get('addtocart/{id}','ShopingCartController@addtocart')->name('addtocart');
Route::post('Addtocart/{id}','AddtocartController@Add');
Route::get('/carts/delete/{id}','AddtocartController@delete')->name('carts.delete');
Route::get('carts/incr/{id}/{qty}','AddtocartController@incr')->name('carts.incr');
Route::get('carts/decr/{id}/{qty}','AddtocartController@decr')->name('carts.decr');
Route::resource('content','ProducteController');










Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/front-end/about.blade.php
@extends('layouts.master')
@section('content')
        
        <!-- breadcrumb start-->
        <section class="breadcrumb breadcrumb_bg">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="breadcrumb_iner">
                            <div class="breadcrumb_iner_item">
                                <p>Home / About</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- breadcrumb start-->
    
        <!-- about part here -->
        <section class="about_part section_padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="about_tittle">
                            <p>Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="single_about_part">
                            <img src="{{asset('front-end/img/about_img_1.png')}}" alt="#">
                            <h4>About Company</h4>
                            <p>Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="single_about_part">
                            <img src="{{asset('front-end/img/about_img_2.png')}}" alt="#">
                            <h4>Philosophy</h4>
                            <p>Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- about part end -->
    
        <!-- free shipping here -->
        <section class="shipping_details section_padding border_top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="single_shopping_details">
                            <img src="{{asset('front-end/img/icon/icon_1.png')}}" alt="">
                            <h4>Free shipping</h4>
                            <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single_shopping_details">
                            <img src="{{asset('front-end/img/icon/icon_2.png')}}" alt="">
                            <h4>Free shipping</h4>
                            <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single_shopping_details">
                            <img src="{{asset('front-end/img/icon/icon_3.png')}}" alt="">
                            <h4>Free shipping</h4>
                            <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="single_shopping_details">
                            <img src="{{asset('front-end/img/icon/icon_4.png')}}" alt="">
                            <h4>Free shipping</h4>
                            <p>Divided face for bearing the divide unto seed winged divided light Forth.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- free shipping end -->
        
        <!-- subscribe_area part start-->
        <section class="instagram_photo">
            <div class="container-fluid>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="instagram_photo_iner">
                            <div class="single_instgram_photo">
                                <img src="{{asset('front-end/img/instagram/inst_1.png')}}" alt="">
                                <a href="#"><i class="ti-instagram"></i></a> 
                            </div>
                            <div class="single_instgram_photo">
                                <img src="{{asset('front-end/img/instagram/inst_2.png')}}" alt="">
                                <a href="#"><i class="ti-instagram"></i></a> 
                            </div>
                            <div class="single_instgram_photo">
                                <img src="{{asset('front-end/img/instagram/inst_3.png')}}" alt="">
                                <a href="#"><i class="ti-instagram"></i></a> 
                            </div>
                            <div class="single_instgram_photo">
                                <img src="{{asset('front-end/img/instagram/inst_4.png')}}" alt="">
                                <a href="#"><i class="ti-instagram"></i></a> 
                            </div>
                            <div class="single_instgram_photo">
                                <img src="{{asset('front-end/img/instagram/inst_5.png')}}" alt="">
                                <a href="#"><i class="ti-instagram"></i></a> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--::subscribe_area part end::-->
    @endsection

resources/views/front-end/billinginfo.blade.php
@extends('layouts.master')

@section('content')

    <!-- Header part end-->

    <!--================Home Banner Area =================-->
    <!-- breadcrumb start-->

    <div class="content-wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                        @if($errors->any())
                            <div class="alert alert-danger">

                                @foreach($errors->all() as $error)
                                    {{$error}}
                                @endforeach


                            </div>
                        @endif

                        @if(session('message'))
                            <div class="alert alert-success">
                                {{session('message')}}
                            </div>
                    @endif
                    <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Billing adress</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            {!! Form::open(array('url' => 'billinginfo','method' => 'post' , 'enctype'=>"multipart/form-data")) !!}
                            <div class="card-body">
                                <div class="form-group">

                                    {{Form::hidden('user_id',Auth::id())}}


                                </div>
                                <div class="form-group">

                                    {{ Form::label("first name", null, ['class' => 'control-label']) }}


                                    {{Form::text('first_name',null,["class" => "form-control",
                "placeholder" => "first name ","id"=>"title"])}}

                                </div>
                                <div class="form-group">

                                    {{ Form::label("last name", null, ['class' => 'control-label']) }}


                                    {{Form::text('last_name',null,["class" => "form-control",
                "placeholder" => "last name","id"=>"last_name"])}}

                                </div>
                                <div class="form-group">

                                    {{ Form::label("company_name", null, ['class' => 'control-label']) }}


                                    {{Form::text('company_name',null,["class" => "form-control",
                "placeholder" => "company_name","id"=>"company_name"])}}

                                </div>
                                <div class="form-group">

                                    {{ Form::label("address", null, ['class' => 'control-label']) }}


                                    {{Form::text('address',null,["class" => "form-control",
                "placeholder" => "address","id"=>"address"])}}

                                </div>


                                <div class="form-group">

                                    {{ Form::label("district", null, ['class' => 'control-label']) }}


                                    {{Form::text('district',null,["class" => "form-control",
                "placeholder" => "district","id"=>"district"])}}

                                </div>
                                <div class="form-group">

                                    {{ Form::label("country", null, ['class' => 'control-label']) }}


                                    {{Form::text('country',null,["class" => "form-control",
                "placeholder" => "country","id"=>"country"])}}

                                </div>
                                <div class="form-group">

                                    {{ Form::label("zipcode", null, ['class' => 'control-label']) }}


                                    {{Form::text('zipcode',null,["class" => "form-control",
                "placeholder" => "zipcode","id"=>"zipcode"])}}

                                </div>



                                <!-- /.card-body -->

                                <div class="card-footer">
                                    {{--                                <button type="submit" class="btn btn-primary">Submit</button>--}}
                                    {{Form::submit('Submit',['class' => 'btn btn-primary'])}}

                                </div>
                                {!! Form::close() !!}
                            </div>
                            <!-- /.card -->
                        </div>







        </section>
    </div>


    <!-- /.content -->
    </div>

    <!--::subscribe_area part end::-->

    <!--::footer_part start::-->
@endsection

resources/views/front-end/cart.blade.php
@extends('layouts.master')
@php
use Gloudemans\Shoppingcart\Facades\Cart
@endphp
@section('content')

  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
      <div class="container">
          <div class="row justify-content-center">
              <div class="col-lg-12">
                  <div class="breadcrumb_iner">
                      <div class="breadcrumb_iner_item">
                          <p>Home/Shop/Single product/Cart list</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!-- breadcrumb start-->

  <!--================Cart Area =================-->
  <section class="cart_area section_padding">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                  <th scope="col">delete</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>

                @foreach(Cart::content() as $product)
                  <tr>
              <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="{{asset("images/productlist/".$product->model->picture)}}" alt="" />
                    </div>
                    <div class="media-body">
                      <p>{{$product->name}}</p>

                    </div>
                  </div>
                </td>
                      <td class="product-remove">
                       <a href="{{route('carts.delete',['id'=>$product->rowId])}}" class="product-del remove" title="remove this item" >
                  <button class="jsgrid-delete-button">delte item</button>
                       </a>
                      </td>
                <td>
                  <h5>{{$product->price}}</h5>
                </td>
                <td>
                  <div class="product_count">
                      <a href="{{url("carts/decr/$product->rowId/$product->qty")}}">

                      <span class="input-number-decrement"> <i class="ti-minus"></i></span>
                      </a>
                      <input class="input-number" type="text" value="{{$product->qty}}" >
                          <a href="{{url("carts/incr/$product->rowId/$product->qty")}}">
                      <span class="input-number-increment"> <i class="ti-plus"></i></span>
                      </a>
                  </div>
                </td>

                <td>
                  <h5>{{$product->total()}}</h5>
                </td>
                  </tr>
                  @endforeach

              <tr class="bottom_button">
                <td>
                  <a class="btn_1" href="#">Update Cart</a>
                </td>
                <td></td>
                <td></td>
                <td>
                  <div class="cupon_text float-right">
                    <a class="btn_1" href="#">Close Coupon</a>
                  </div>
                </td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <h5>Subtotal</h5>
                </td>
                <td>
                  <h5>{{Cart::total()}}</h5>
                </td>
              </tr>
              <tr class="shipping_area">
                <td></td>
                <td></td>
                <td>
                  <h5>Shipping</h5>
                </td>
                <td>
                  <div class="shipping_box">
                    <ul class="list">
                      <li>
                        Flat Rate: $5.00
                        <input type="radio" aria-label="Radio button for following text input">
                      </li>
                      <li>
                        Free Shipping
                        <input type="radio" aria-label="Radio button for following text input">
                      </li>
                      <li>
                        Flat Rate: $10.00
                        <input type="radio" aria-label="Radio button for following text input">
                      </li>
                      <li class="active">
                        Local Delivery: $2.00
                        <input type="radio" aria-label="Radio button for following text input">
                      </li>
                    </ul>
                    <h6>
                      Calculate Shipping
                      <i class="fa fa-caret-down" aria-hidden="true"></i>
                    </h6>
                    <select class="shipping_select">
                      <option value="1">Bangladesh</option>
                      <option value="2">India</option>
                      <option value="4">Pakistan</option>
                    </select>
                    <select class="shipping_select section_bg">
                      <option value="1">Select a State</option>
                      <option value="2">Select a State</option>
                      <option value="4">Select a State</option>
                    </select>
                    <input class="post_code" type="text" placeholder="Postcode/Zipcode" />
                    <a class="btn_1" href="#">Update Details</a>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <a class="btn_1" href="#">Continue Shopping</a>
            <a class="btn_1 checkout_btn_1" href="#">Proceed to checkout</a>
          </div>
        </div>
      </div>
  </section>
  <!--================End Cart Area =================-->

 @endsection

resources/views/front-end/checkout.blade.php
@extends('layouts.master')

@section('content')


    <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <p>Home / checkout</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->

  <!--================Checkout Area =================-->
  <section class="checkout_area section_padding">
    <div class="container">
      <div class="cupon_area">
        <div class="check_title">
          <h2>
            Have a coupon?
            <a href="#">Click here to enter your code</a>
          </h2>
        </div>
        <input type="text" placeholder="Enter coupon code" />
        <a class="tp_btn" href="#">Apply Coupon</a>
      </div>
        @if(!empty($user->billinginfo->user_id))
      <div class="billing_details">
        <div class="row">
          <div class="col-lg-8">
            <h3>Billing Details</h3>
            <form class="row contact_form" action="#" method="post" novalidate="novalidate">
              <div class="col-md-6 form-group p_star">
                <h1>
                <span class="placeholder" data-placeholder="First name: {{$user->Billinginfo->first_name}}"></span>
                </h1>
              </div>

                <br>
              <div class="col-md-6 form-group p_star">
                  <h2><br></h2>
                  <h1>
                <span class="placeholder" data-placeholder="Last name: {{$user->Billinginfo->last_name}}"></span>
                  </h1>
              </div>
                <br>

                <br>
              <div class="col-md-6 form-group p_star">
                  <h2><br></h2>
                 <h1>

                <span class="placeholder" data-placeholder="Phone number :"></span>
                 </h1>
              </div>
                <br>
              <div class="col-md-12 form-group p_star">
                  <h2><br></h2>
                <h1>
                <span class="placeholder" data-placeholder="Email Address :{{$user->email}}"></span>
                </h1>
              </div>
                <br>
              <div class="col-md-12 form-group p_star">
                  <h2><br></h2>
                  <h1>
                  <span class="placeholder" data-placeholder="country :{{$user->Billinginfo->country}}"></span>
                  </h1>
              </div>
                <br>

              <div class="col-md-12 form-group p_star">
               <h2><br></h2>
                  <h1 style="">
                <span class="placeholder" data-placeholder="Address line:{{$user->Billinginfo->address}}"></span>
                  </h1>
              </div>
                <br>


              <div class="col-md-12 form-group">
                  <h2><br></h2>
                  <h1>
                  <span class="placeholder" data-placeholder="Email Address :{{$user->Billinginfo->zip}}"></span>

                  </h1>
              </div>
                <br>

              <div class="col-md-12 form-group">
                <div class="creat_account">
                  <h3>Shipping Details</h3>
                  <input type="checkbox" id="f-option3" name="selector" />
                  <label for="f-option3">Ship to a different address?</label>
                </div>
{{--                  {!! Form::open(array(url("billinginfo/{billinginfo}"),'method' => 'put')) !!}--}}
{{--                  {{Form::textarea('address',null,["class" => "form-control",--}}
{{--             "placeholder" => "different address ","id"=>"title"])}}--}}
{{--                  <div class="card-footer">--}}
{{--                      <button type="submit" class="btn btn-primary">Submit</button>--}}
{{--                      {{Form::submit('Submit',['class' => 'btn btn-primary'])}}--}}

{{--                  </div>--}}
{{--                  {!! Form::close() !!}--}}
              </div>
            </form>

          </div>
            @else
                <div class="btn">
                    <a class="btn_3" href="{{route('billinginfo.index')}}">Create your billing address to place your order</a>
                    <br>
                </div>
            @endif
          <div class="col-lg-4">
            <div class="order_box">
              <h2>Your Order</h2>
              <ul class="list">
                <li>
                  <a href="#">Product
                    <span>Total</span>
                  </a>
                </li>
                  @foreach(Cart::content() as $item)
                <li>
                  <a href="#">{{$item->name}}
                    <span class="middle">x {{$item->qty}}</span>
                    <span class="last">${{$item->total()}}</span>
                  </a>
                </li>
                  @endforeach

              </ul>
              <ul class="list list_2">
                <li>
                  <a href="#">Subtotal
                    <span>${{Cart::total()}}</span>
                  </a>
                </li>
                <li>
                  <a href="#">Shipping
                    <span>Flat rate: $50.00</span>
                  </a>
                </li>
                <li>
                  <a href="#">Total
                    <span>${{Cart::total()+50}}</span>
                  </a>
                </li>
              </ul>
                <div class='form-control total btn btn-info'>

                    <a href="{{route('payindex')}}">
                        Total:
                        <span class='amount'>${{Cart::total()+50}}</span>
                    </a>
                </div>
                <div class="payment_item">




          </div>
        </div>
      </div>
    </div>
  </section>



<div class='form-control total btn btn-info'>
    Total:
    <span class='amount'>$300</span>
</div>
<div>

</div>


  <!--================End Checkout Area =================-->

  <!-- subscribe_area part start-->

  <!--::subscribe_area part end::-->

@endsection

resources/views/front-end/tracking.blade.php
@extends('layouts.master')

@section('content')

    <!-- Header part end-->
  
  <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
      <div class="container">
          <div class="row justify-content-center">
              <div class="col-lg-12">
                  <div class="breadcrumb_iner">
                      <div class="breadcrumb_iner_item">
                          <p>Home / tracking</p>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!-- breadcrumb start-->

  <!--================Tracking Box Area =================-->
  <section class="tracking_box_area section_padding">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-lg-12">
          <div class="tracking_box_inner">
            <p>To track your order please enter your Order ID in the box below and press the "Track" button. This was
              given
              to you on your receipt and in the confirmation email you should have received.</p>
            <form class="row tracking_form" action="#" method="post" novalidate="novalidate">
              <div class="col-md-12 form-group">
                <input type="text" class="form-control" id="order" name="order" placeholder="Order ID">
              </div>
              <div class="col-md-12 form-group">
                <input type="email" class="form-control" id="email" name="email" placeholder="Billing Email Address">
              </div>
              <div class="col-md-12 form-group">
                <button type="submit" value="submit" class="btn_3">Track Order</button>
              </div>
            </form>
          </div>
        </div>

      </div>

    </div>
  </section>
  <!--================End Tracking Box Area =================-->

  <!-- subscribe_area part start-->
  <section class="instagram_photo">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="instagram_photo_iner">
                    <div class="single_instgram_photo">
                        <img src="{{asset('front-end/img/instagram/inst_1.png')}}" alt="">
                        <a href="#"><i class="ti-instagram"></i></a> 
                    </div>
                    <div class="single_instgram_photo">
                        <img src="{{asset('front-end/img/instagram/inst_2.png')}}" alt="">
                        <a href="#"><i class="ti-instagram"></i></a> 
                    </div>
                    <div class="single_instgram_photo">
                        <img src="{{asset('front-end/img/instagram/inst_3.png')}}" alt="">
                        <a href="#"><i class="ti-instagram"></i></a> 
                    </div>
                    <div class="single_instgram_photo">
                        <img src="{{asset('front-end/img/instagram/inst_4.png')}}" alt="">
                        <a href="#"><i class="ti-instagram"></i></a> 
                    </div>
                    <div class="single_instgram_photo">
                        <img src="{{asset('front-end/img/instagram/inst_5.png')}}" alt="">
                        <a href="#"><i class="ti-instagram"></i></a> 
                    </div>
                </div>
            </div>
        </div>
    </div>
  </section>
  <!--::subscribe_area part end::-->

@endsection